{
    'name': 'Customer Type Added at Contact Form',
    'version': '12.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'Customer Type Added at Contact Form',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'NN',
    'maintainer': 'NN',
    'website': 'https://sokehpwarlay.blogspot.com/',
    'depends': ['base', 'stock', 'inherit_form'],
    'demo': [],
    'data': [
    'views/partner_view.xml',
    ],
    'images': ['static/description/icons.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
